### Create Outfit
POST http://localhost:8000/outfitmatcher/api/v1/outfit
Content-Type: application/json

{
    "outfit": "generate image of a muslim  outfit suitable for going to mosque in rainy weather"
}

### Save Outfit
POST http://localhost:8000/outfitmatcher/api/v1/outfit/save
Content-Type: application/json

{
  "outfitId": "670a06defa8e2ff94ff624b4"
} 


### GET Outfit
GET http://localhost:8000/outfitmatcher/api/v1/outfit

### DELETE Outfit
DELETE http://localhost:8000/outfitmatcher/api/v1/outfit/6706c9635654e491a202f27b

### Cpllections

### GET outfit by user
GET http://localhost:8000/outfitmatcher/api/v1/outfit/collections

### DELETE outfit by user
DELETE http://localhost:8000/outfitmatcher/api/v1/outfit/collections/6706c9635654e491a202f27b