### Create User
POST http://localhost:8000/outfitmatcher/api/v1/register
Content-Type: application/json

{
    "firstName": "Asep",
    "lastName": "Sunarya",
    "username": "asep988",
    "email": "asep@gmail.com",
    "password": "asep12345_"
}

### Login User
POST http://localhost:8000/outfitmatcher/api/v1/login
Content-Type: application/json

{
    "email": "asep@gmail.com",
    "password": "asep12345_"
}

### Logout User
POST http://localhost:8000/outfitmatcher/api/v1/logout