### Create User
POST http://localhost:8000/outfitmatcher/api/v1/register
Content-Type: application/json

{
    "firstName": "Faqih",
    "lastName": "Nur Fahmi",
    "username": "faqih1993",
    "email": "faqih@gmail.com",
    "password": "faqih123456!"
}

### Login User
POST http://localhost:8000/outfitmatcher/api/v1/login
Content-Type: application/json

{
    "email": "faqih@gmail.com",
    "password": "faqih123456!"
}

### Logout User
POST http://localhost:8000/outfitmatcher/api/v1/logout


=======
### Update User
PATCH http://localhost:8000/outfitmatcher/api/v1/update
Content-Type: application/json

{
    "firstName": "Asep",
    "lastName": "Sunarya",
    "username": "asep988",
    "email": "asep@gmail.com",
    "password": "Asep12345!"
}

### Delete User
DELETE http://localhost:8000/outfitmatcher/api/v1/delete/6700817ad357410dd5d94d33

