### Create User
POST http://localhost:8000/outfitmatcher/api/v1/register
Content-Type: application/json

{
    "firstName": "Putra",
    "lastName": "Siregar",
    "username": "putra3345",
    "email": "psiregar@gmail.com",
    "password": "psiregar12345_"
}

### Login User
POST http://localhost:8000/outfitmatcher/api/v1/login
Content-Type: application/json

{
    "email": "psiregar@gmail.com",
    "password": "psiregar12345_"
}

### Logout User
POST http://localhost:8000/outfitmatcher/api/v1/logout


### Outfit
POST http://localhost:8000/outfitmatcher/
Content-Type: application/json

{
    "outfit": "generate image of a men's outfit suitable for going to campus in rainy weather"
}

### Update User
PATCH http://localhost:8000/outfitmatcher/api/v1/update
Content-Type: application/json

{
    "firstName": "Asep",
    "lastName": "Sunarya",
    "username": "asep988",
    "email": "asep@gmail.com",
    "password": "Asep12345!"
}

### Delete User
DELETE http://localhost:8000/outfitmatcher/api/v1/delete/6700817ad357410dd5d94d33

